// @flow
import type { PhysicalBusErrorType } from './types';

/**
 * Function that creates an error for I/O erros
 * (i.e device not available)
 */
export const createIOError = (): PhysicalBusErrorType => {
  const error: PhysicalBusErrorType = new Error('Remote I/O error');
  error.errno = 121;
  error.cause = new Error('Generated by a mock bus');

  return error;
};

/**
 * Function that creates an error for a bus not found
 * (i.e bus number not available or nor configured)
 */
export const createNotFoundError = (busNumber: number): PhysicalBusErrorType => {
  const error: PhysicalBusErrorType = new Error(`ENOENT: no such file or directory, open '/dev/i2c-${busNumber}'`);
  error.errno = -2;
  error.cause = new Error('Generated by a mock bus');

  return error;
};
