version: 2
jobs:
  build:
    docker:
      - { image: 'circleci/node:8.9-stretch' }
    steps:
      - checkout
      - { run: { name: update-npm, command: 'sudo npm install -g npm@latest' } }
      - { restore_cache: { key: 'dependency-cache-{{ checksum "package.json" }}' } }
      - { run: { name: 'install yarn', command: 'sudo npm i -g yarn' } }
      - { run: { name: 'install deps', command: 'yarn install' } }
      - { save_cache: { key: 'dependency-cache-{{ checksum "package.json" }}', paths: [./node_modules] } }
      - { run: { name: flow-typed, command: 'yarn flow-typed' } }
      - { run: { name: flow, command: 'yarn flow' } }
      - { run: { name: lint, command: 'yarn lint' } }
  deploy:
    docker:
      - { image: 'circleci/node:8.9-stretch' }
    steps:
      - checkout
      - { run: { name: 'Write NPM Token to ~/.npmrc', command: 'echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc' } }
      - { run: { name: 'yarn build', command: 'yarn build' } }
      - { run: { name: 'Publish to NPM', command: 'npm publish --access=public' } }
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master